server:
   port: 8031
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
   instance:
      instance-id: ${spring.application.name}
      hostname: localhost
      statusPageUrlPath: /actuator/health
spring:
   application:
      name: ms-person
   data:
      mongodb:
         uri: "mongodb://localhost:27017/petshop"
